import type { Metadata } from "next";
import { Inter, Nanum_Gothic_Coding } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";

const googleFont = Nanum_Gothic_Coding({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={googleFont.className}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
